spring:
  application:
    name: car_management

  datasource:
    url: jdbc:mysql://localhost:3306/car_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Bangkok
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

cloudinary:
  cloud-name: dntzdrmc8
  api-key: 392795975793191
  api-secret: XXXXXX-xxxx-XXXXXX


server:
  port: 8081
